docs(ddl): :memo: describe each DDL test function
CleverseAcademy/sql-exercise pull request #5
Opened 2023-10-27 15:40 UTC by intaniger

Fix #4

2023-10-27 16:18 UTC, bunnanna requested changes
The tables' schema and detail are needed when CREATE and after mutations. 
Then add all detail to doc.

2023-10-27 16:18 UTC, bunnanna commented on src/ddl/appointment/doctor.ts
> +// Create table with all necessary columns and `department` of 64-character varying type
No need to say about row exception.

2023-10-27 16:18 UTC, bunnanna commented on src/ddl/organization/applicant.ts
> +// Create applicant table with all necessary columns and `phone` of INT type and cv of type text
No need to say about row exception.

2023-10-27 16:18 UTC, bunnanna commented on src/ddl/organization/job_availability.ts
> +// Create applicant table with all necessary columns and `duration` of type INT  and `cost_per_hour` of type INT
No need to say about row exception.

2023-10-28 06:09 UTC, intaniger commented on src/ddl/appointment/availability.ts
>  export const createTableStmt = ddl(`CREATE `);
added to https://github.com/CleverseAcademy/sql-exercise/tree/fix/ddl-doc/docs/ddl#tables-definition-1

2023-10-28 06:39 UTC, merged